# Generated by Django 3.2 on 2023-05-08 05:31

import django.core.validators
from django.db import migrations, models

import recipes.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AmountIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Минимальное количество 1."
                            )
                        ],
                        verbose_name="Количество",
                    ),
                ),
            ],
            options={
                "verbose_name": "Количество ингредиента",
                "verbose_name_plural": "Количество Ингредиентов",
                "ordering": ("recipe",),
            },
        ),
        migrations.CreateModel(
            name="Carts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепт в списке покупок",
                "verbose_name_plural": "Рецепты в списке покупок",
            },
        ),
        migrations.CreateModel(
            name="Favorites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранный рецепт",
                "verbose_name_plural": "Избранные рецепты",
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обязательное для заполнения поле. Максимум 200 символов.",
                        max_length=200,
                        validators=[
                            django.core.validators.MaxLengthValidator(200)
                        ],
                        verbose_name="Ингредиент",
                    ),
                ),
                (
                    "measurement_unit",
                    models.CharField(
                        help_text="Обязательное для заполнения поле. Максимум 200 символов.",
                        max_length=200,
                        validators=[
                            django.core.validators.MaxLengthValidator(200)
                        ],
                        verbose_name="Единица измерения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обязательное для заполнения поле. Максимум 200 символов.",
                        max_length=200,
                        validators=[
                            django.core.validators.MaxLengthValidator(200)
                        ],
                        verbose_name="Название рецепта",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="recipe_images/",
                        verbose_name="Изображение рецепта",
                    ),
                ),
                ("text", models.TextField(verbose_name="Описание рецепта")),
                (
                    "cooking_time",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Минимальное время приготовления 1 минута"
                            )
                        ],
                        verbose_name="Время приготовления в минутах",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
                "ordering": ("-pub_date",),
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "unique": "Тег с таким названием уже существует."
                        },
                        help_text="Обязательное для заполнения поле. Максимум 200 символов.",
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(200),
                            recipes.validators.HexColorValidator(),
                        ],
                        verbose_name="Название тега",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#008080",
                        error_messages={
                            "unique": "Тег с таким цветом уже существует."
                        },
                        help_text="Обязательное для заполнения поле. Максимум 7 символов.",
                        max_length=7,
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(7),
                            recipes.validators.HexColorValidator(),
                        ],
                        verbose_name="Цвет в HEX",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        error_messages={
                            "unique": "Тег с таким слагом уже существует."
                        },
                        help_text="Обязательное для заполнения поле. Максимум 200 символов.",
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(200)
                        ],
                        verbose_name="Уникальный слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ("name",),
            },
        ),
    ]
